//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACMEntities : DbContext
    {
        public ACMEntities()
            : base("name=ACMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
        public DbSet<AuditEntry> AuditEntries { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Email> Emails { get; set; }
        public DbSet<EmailTo> EmailToes { get; set; }
        public DbSet<OFI> OFIs { get; set; }
        public DbSet<OFIAssigned> OFIAssigneds { get; set; }
        public DbSet<OFICategory> OFICategories { get; set; }
        public DbSet<OFIDueDate> OFIDueDates { get; set; }
        public DbSet<OFIEntry> OFIEntries { get; set; }
        public DbSet<OFIFile> OFIFiles { get; set; }
        public DbSet<OFIOrigin> OFIOrigins { get; set; }
        public DbSet<OFIType> OFITypes { get; set; }
        public DbSet<Priority> Priorities { get; set; }
        public DbSet<ReportCategory> ReportCategories { get; set; }
        public DbSet<ReportFile> ReportFiles { get; set; }
        public DbSet<Report> Reports { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<Status> Statuses { get; set; }
    }
}
